[package]
name = "bandori-score-best-calculator"
version = "0.1.0"
description = "Portable Bandori best-team score calculator"
authors = ["Stakataka-3030"]
edition = "2021"

[lib]
name = "bandori_score_best_calculator_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-http = "2"
